version: "3"
services:
  database_tiw:
    image: postgres:latest
    container_name: database_tiw
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database_tiw
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8888:8080

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: audesandrine6@gmail.com 
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_project_iw3
    image: app_project_iw3
    restart: always
    volumes:
      - ./www:/var/www
    environment:
      - DB_HOST=46.226.107.16
      - DB_PORT=5432
      - DB_DATABASE=database_tiw
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres


  app_project_nginx:
    image: nginx:latest
    container_name: app_project_nginx
    restart: always
    ports:
      - 88:80
      - "447:443"
    volumes:
      - ./www:/var/www
      - ./config/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      

  postfix:
    image: ubuntu:latest
    container_name: postfix
    restart: always
    ports:
       - 25:25
    volumes:
      - ./postfix/main.cf:/etc/postfix/main.cf
      - ./postfix/master.cf:/etc/postfix/master.cf
    command: postfix start-fg

