default:
  controller: Main
  action: home

a-propos:
  controller: Main
  action: aboutUs

about-us:
  controller: Main
  action: aboutUs

contact:
  controller: Main
  action: contact

login:
  controller: Auth
  action: login

register:
  controller: Auth
  action: register

activate:
  controller: Auth
  action: activate

logout:
  controller: Auth
  action: logout

forgotpassword:
  controller: Auth
  action: forgotPassword

resetpassword:
  controller: Auth
  action: resetPassword

newpassword:
  controller: Auth
  action: newPassword  

s-inscrire:
  controller: Auth
  action: register

admin/showuser:
  controller: UserController
  action: showUser

admin/user/delete:
  controller: UserController
  action: deleteUser

admin/user/edit:
  controller: UserController
  action: editUser

admin/user/add:
  controller: UserController
  action: addUser  