default:
  controller: Main
  action: home

a-propos:
  controller: Main
  action: aboutUs

about-us:
  controller: Main
  action: aboutUs

contact:
  controller: Main
  action: contact

login:
  controller: Auth
  action: login

register:
  controller: Auth
  action: register

logout:
  controller: Auth
  action: logout

forgotpassword:
  controller: Auth
  action: forgotPassword

resetpassword:
  controller: Auth
  action: resetPassword

s-inscrire:
  controller: Auth
  action: register