default:
  controller: Main
  action: home
  verifConnexion: true

a-propos:
  controller: Main
  action: aboutUs

about-us:
  controller: Main
  action: aboutUs

contact:
  controller: Main
  action: contact

login:
  controller: Auth
  action: login
  

error:
  controller: Auth
  action: notFound  

register:
  controller: Auth
  action: register

activate:
  controller: Auth
  action: activate

logout:
  controller: Auth
  action: logout

forgotpassword:
  controller: Auth
  action: forgotPassword

resetpassword:
  controller: Auth
  action: resetPassword 

newpassword:
  controller: Auth
  action: newPassword  

s-inscrire:
  controller: Auth
  action: register

admin:
  controller: AdminController
  action: index
  security: ROLE:ADMIN

admin/showuser:
  controller: UserController
  action: showUser
  security: ROLE:ADMIN 

admin/user/delete:
  controller: UserController
  action: deleteUser
  security: ROLE:ADMIN 

admin/user/edit:
  controller: UserController
  action: editUser
  security: ROLE:ADMIN 

admin/user/add:
  controller: UserController
  action: addUser 
  security: ROLE:ADMIN  
  verifConnexion: true

admin/user/role:
  controller: UserController
  action: editRole
  security: ROLE:ADMIN  

admin/page/index:
  controller: PageController
  action: showPost
  security: ROLE:ADMIN

admin/page/edit:
  controller: PageController
  action: editPost
  security: ROLE:ADMIN

admin/page/delete:
  controller: PageController
  action: deletePost
  security: ROLE:ADMIN  

admin/page/add:
  controller: PageController
  action: addPost
  security: ROLE:ADMIN

admin/page/pending:
  controller: PageController
  action: pendingPost
  security: ROLE:ADMIN

admin/page/publish:
  controller: PageController
  action: publishPost
  security: ROLE:ADMIN 
  
post/{slug}:
  controller: PostController
  action: showPost

admin/article/index:
  controller: ArticleController
  action: showArticle
  security: ROLE:ADMIN

admin/article/edit:
  controller: ArticleController
  action: editArticle
  security: ROLE:ADMIN

admin/article/delete:
  controller: ArticleController
  action: deleteArticle
  security: ROLE:ADMIN

admin/article/publish:
  controller: ArticleController
  action: publishArticle
  security: ROLE:ADMIN

admin/article/add:
  controller: ArticleController
  action: addArticle
  security: ROLE:ADMIN

admin/article/pending:
  controller: ArticleController
  action: pendingArticle
  security: ROLE:ADMIN

article/{slug}:
  controller: ArticleController
  action: previewArticle

admin/menu/index:
  controller: MenuController
  action: showMenu
  security: ROLE:ADMIN

admin/menu/edit:
  controller: MenuController
  action: editMenu
  security: ROLE:ADMIN

admin/menu/delete:
  controller: MenuController
  action: deleteMenu
  security: ROLE:ADMIN

admin/menu/add:
  controller: MenuController
  action: addMenu
  security: ROLE:ADMIN

admin/menu/pending:
  controller: MenuController
  action: pendingMenu
  security: ROLE:ADMIN

admin/menu/publish:
  controller: MenuController
  action: publishMenu
  security: ROLE:ADMIN

admin/comment/index:
  controller: CommentController
  action: showComments

admin/comment/edit:
  controller: CommentController
  action: updateComment

addcomment:
  controller: CommentController
  action: addComment

signalcomment:
  controller: CommentController
  action: signalComment
